BudgetMVC/ViewModels/ModalTemplateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace BudgetMVC.ViewModels
{
    public class ModalTemplateViewModel
    {
        [Required]
        public string Description { get; set; }
        public DateTime Date { get; set; }
        public double Value { get; set; }
        public string EntityName { get; set; }
    }
}

BudgetMVC/Controllers/ContributionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using BudgetMVC.Model.Entity;
using BudgetMVC.Model.EntityFramework;
using BudgetMVC.Model.Business;

namespace BudgetMVC.Controllers
{
    public class ContributionController : ApiController
    {
        private ContributionBusiness contributionBusiness;

        public ContributionController()
        {
            this.contributionBusiness = new ContributionBusiness(new BudgetContext());
        }
        // GET api/Contribution
        public IEnumerable<Contribution> GetContributions()
        {
            return contributionBusiness.FindAll();
        }

        // GET api/Contribution/5
        public Contribution GetContribution(long id)
        {
            Contribution contribution = contributionBusiness.Find(id);
            if (contribution == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return contribution;
        }

        // PUT api/Contribution/5
        public HttpResponseMessage PutContribution(long id, Contribution contribution)
        {
            if (ModelState.IsValid && id == contribution.ID)
            {
                try
                {
                    contributionBusiness.Update(contribution);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return Request.CreateResponse(HttpStatusCode.NotFound);
                }

                return Request.CreateResponse(HttpStatusCode.OK, contribution);
            }
            else
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        // POST api/Contribution
        public HttpResponseMessage PostContribution(Contribution contribution)
        {
            if (ModelState.IsValid)
            {
                contributionBusiness.Insert(contribution);
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.Created, contribution);
                response.Headers.Location = new Uri(Url.Link("DefaultApi", new { id = contribution.ID }));
                return response;
            }
            else
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        // DELETE api/Contribution/5
        public HttpResponseMessage DeleteContribution(long id)
        {
            Contribution removedContribution;
            try
            {
                removedContribution = contributionBusiness.RemoveById(id);
            }
            catch (Exception)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            return Request.CreateResponse(HttpStatusCode.OK, removedContribution);
        }

        protected override void Dispose(bool disposing)
        {
            contributionBusiness.Dispose();
            base.Dispose(disposing);
        }
    }
}

BudgetMVC/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BudgetMVC.Model.Entity;
using BudgetMVC.Model.EntityFramework;

namespace BudgetMVC.Controllers
{
    public class ExpensesController : Controller
    {
        private BudgetContext db = new BudgetContext();

        //
        // GET: /Expenses/

        public ActionResult Index()
        {
            return View(db.Expenses.ToList());
        }

        //
        // GET: /Expenses/Details/5

        public ActionResult Details(long id = 0)
        {
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        //
        // GET: /Expenses/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Expenses/Create

        [HttpPost]
        public ActionResult Create(Expense expense)
        {
            if (ModelState.IsValid)
            {
                db.Expenses.Add(expense);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(expense);
        }

        //
        // GET: /Expenses/Edit/5

        public ActionResult Edit(long id = 0)
        {
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        //
        // POST: /Expenses/Edit/5

        [HttpPost]
        public ActionResult Edit(Expense expense)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expense).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expense);
        }

        //
        // GET: /Expenses/Delete/5

        public ActionResult Delete(long id = 0)
        {
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        //
        // POST: /Expenses/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            Expense expense = db.Expenses.Find(id);
            db.Expenses.Remove(expense);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BudgetMVC/Controllers/RevenuesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BudgetMVC.Model.Entity;
using BudgetMVC.Model.EntityFramework;

namespace BudgetMVC.Controllers
{
    public class RevenuesController : Controller
    {
        private BudgetContext db = new BudgetContext();

        //
        // GET: /Revenues/

        public ActionResult Index()
        {
            return View(db.Revenues.ToList());
        }

        //
        // GET: /Revenues/Details/5

        public ActionResult Details(long id = 0)
        {
            Revenue revenue = db.Revenues.Find(id);
            if (revenue == null)
            {
                return HttpNotFound();
            }
            return View(revenue);
        }

        //
        // GET: /Revenues/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Revenues/Create

        [HttpPost]
        public ActionResult Create(Revenue revenue)
        {
            if (ModelState.IsValid)
            {
                db.Revenues.Add(revenue);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(revenue);
        }

        //
        // GET: /Revenues/Edit/5

        public ActionResult Edit(long id = 0)
        {
            Revenue revenue = db.Revenues.Find(id);
            if (revenue == null)
            {
                return HttpNotFound();
            }
            return View(revenue);
        }

        //
        // POST: /Revenues/Edit/5

        [HttpPost]
        public ActionResult Edit(Revenue revenue)
        {
            if (ModelState.IsValid)
            {
                db.Entry(revenue).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(revenue);
        }

        //
        // GET: /Revenues/Delete/5

        public ActionResult Delete(long id = 0)
        {
            Revenue revenue = db.Revenues.Find(id);
            if (revenue == null)
            {
                return HttpNotFound();
            }
            return View(revenue);
        }

        //
        // POST: /Revenues/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            Revenue revenue = db.Revenues.Find(id);
            db.Revenues.Remove(revenue);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BudgetMVC/Views/Shared/_ContributionModalTemplate.cshtml
@model BudgetMVC.ViewModels.ContributionViewModel
<div class="newContribution">
    <div class="row">
        <div class="six mobile-four columns">
            <h3>
                Create new Contribution</h3>
            <form class="custom" action="">
            <fieldset>
                <legend></legend>
                @Html.LabelFor(model => model.Description)
                @Html.EditorFor(model => model.Description)
                <div class="row collapse">
                    <div class="one mobile-one columns">
                        <span class="prefix">R$</span>
                    </div>
                    <div class="five mobile-one columns">
                        @Html.EditorFor(model => model.Value)
                    </div>
                    <div class="two mobile-one columns offset-by-three">
                        @Html.EditorFor(model => model.ContributionFactor)
                    </div>
                    <div class="one mobile-one columns">
                        <span class="postfix">%</span>
                    </div>
                </div>
                @Html.LabelFor(model => model.InitialDate)
                @Html.EditorFor(model => model.InitialDate)
                @Html.DropDownList("Contributor.ID", Model.Contributors, "", new { id = "customDropdown", style = "display:none" })
            </fieldset>
            </form>
            <ul class="button-group even two-up">
                <li><a href="#" class="small button" data-bind="click: saveContribution">Save</a></li>
                <li><a href="#" class="small button" data-bind="click: cancelContribution">Cancel</a></li>
            </ul>
        </div>
    </div>
</div>

BudgetMVC/Views/Shared/_Foundation.cshtml
@using BudgetMVC.Extensions
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <script type="text/javascript">
        CONTEXT = "@Html.GetSiteRoot()";
    </script>
    @Styles.Render("~/Content/foundation/css")
    @Styles.Render("~/Content/pickadate")
    @RenderSection("head", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="top-bar">
        <ul>
            <li class="name">
                <h1>
                    <a href="#">BudgetMVC</a></h1>
            </li>
            <li class="toggle-topbar"><a href="#"></a></li>
        </ul>
        <section>
            <ul class="left">
                <li class="has-dropdown"><a href="#">Contribution</a>
                    <ul class="dropdown">
                        <li><a href="#" data-bind="click: newContribution">New</a></li>
                        <li>@Html.ActionLink("List","Index","Contribution")</li>
                    </ul>
                </li>
                <li class="has-dropdown"><a href="#">Revenue</a>
                    <ul class="dropdown">
                        <li><a href="#" data-bind="click: newRevenue">New</a></li>
                        <li>@Html.ActionLink("List", "Index", "Revenues")</li>
                    </ul>
                </li>
                <li class="has-dropdown"><a href="#">Expense</a>
                    <ul class="dropdown">
                        <li><a href="#" data-bind="click: newExpense">New</a></li>
                        <li>@Html.ActionLink("List", "Index", "Expenses")</li>
                    </ul>
                </li>
            </ul>
            <ul class="right">
                <li><a href="#">Configuration</a></li>
            </ul>
        </section>
    </nav>
    @RenderBody()
    <div id="loading" class="loading">
    </div>
    @Scripts.Render("~/bundles/spin")
    @Scripts.Render("~/bundles/foundation")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ko")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
</body>
</html>

BudgetMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>BudgetMVC - Good finacial management make dreams reality!</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/themes/base/css", "~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("BudgetMVC", "Index", "Home")</p>
                <p class="site-title">
                    Good finacial management make dreams reality!</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
            <div>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        <section class="content-wrapper clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>
                    &copy; @DateTime.Now.Year - BudgetMVC</p>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

BudgetMVC/Views/Shared/_ModalTemplate.cshtml
@model BudgetMVC.ViewModels.ModalTemplateViewModel

<div class="new@(Model.EntityName)" style="display: none;">
    <div class="row">
        <div class="six mobile-four columns">
            <h3>
                Create new @Model.EntityName</h3>
            <form>
            <fieldset>
                @Html.LabelFor(model => model.Description)
                @Html.EditorFor(model => model.Description)
                <div class="row collapse">
                    <div class="two mobile-one columns">
                        <span class="prefix">R$</span>
                    </div>
                    <div class="ten mobile-three columns">
                        @Html.EditorFor(model => model.Value)
                    </div>
                </div>
                @Html.LabelFor(model => model.Date)
                @Html.EditorFor(model => model.Date)
            </fieldset>
            </form>
            <ul class="button-group even two-up">
                <li><a href="#" class="small button" data-bind="click: save@(Model.EntityName)">Save</a></li>
                <li><a href="#" class="small button" data-bind="click: cancel@(Model.EntityName)">Cancel</a></li>
            </ul>
        </div>
    </div>
</div>